export enum PaymentEventType {
  REDIRECT_CREATED = 'REDIRECT_CREATED',
  CALLBACK_RECEIVED = 'CALLBACK_RECEIVED',
  WEBHOOK_RECEIVED = 'WEBHOOK_RECEIVED',
  RECONCILED = 'RECONCILED',
  FAILED = 'FAILED',
  DUPLICATE_IGNORED = 'DUPLICATE_IGNORED',
}
